AllCops:
  NewCops: enable
  Exclude:
    - db/**
    - config/**

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
